### ISSUE TITLE
您好，请问n_pool_kernel_size和n_freq_downsample这两个参数对预测效果的影响大吗？

### ISSUE THREAD

**Issue by 943fansi** [Guan-t7/mv_nhits#1]

**Comment by Guan-t7** [comment]
我们观测到和nhits原文一致的结果，即：坏的插值参数会导致坏的结果；需要做几次超参搜索找到较好的参数。具体参见[原文](https://arxiv.org/pdf/2201.12886.pdf)的A7.1和A9节

**Comment by 943fansi** [comment]
> 我们观测到和nhits原文一致的结果，即：坏的插值参数会导致坏的结果；需要做几次超参搜索找到较好的参数。具体参见[原文](https://arxiv.org/pdf/2201.12886.pdf)的A7.1和A9节

好的，谢谢
